### ISSUE TITLE
Stop tailing logs after log rotation in k8s

### ISSUE THREAD

**Issue by arezvani** [stern/stern#311]
Hi,

I have a problem where Stern stops collecting logs from a pod that produces logs at a high rate after a while. I tried to find out why this happens and discovered that this issue occurs when kubectl logs -f also stops. I found out that this is due to log rotation in Kubernetes. Stern works like tail -f rather than tail -F, which uses inode tracking.

**Comment by tksm** [comment]
Hi,

Which Kubernetes version are you using? I believe this issue is related to [a known Kubernetes bug](https://github.com/kubernetes/kubernetes/issues/115701) that has been resolved in Kubernetes v1.29.0. Please see [this comment](https://github.com/stern/stern/issues/287#issuecomment-1855184230) for details.

**Comment by arezvani** [comment]
I have installed Kubernetes v1.29.0. But this problem not solved and when log file of pod rotate, `kubectl logs -f` stop gives log.

**Comment by arezvani** [comment]
https://github.com/arezvani/tailer

Tailer is a tool designed to dynamically monitor Kubernetes pod logs, ensuring that logs from all containers, including new and recreated pods, are collected without missing critical events. Tailer overcomes Kubernetes’ default connection timeout limitations and provides a robust solution for long-term log collection. Tools like Stern and Kail also face the same challenge due to Kubernetes’ default connection timeout limitations, which can disrupt long-term log monitoring. Tailer overcomes these issues and provides a robust solution for persistent log collection.
